import type { GoalBudgetMode, GoalElement, GoalPolicy, GoalPolicyDimension, GoalPolicyDimensionOverride, GoalRuntimeProjection } from '../../types.ts';
import type { GoalPolicyV1 } from '../../utils/goalPolicy.ts';
import { GOAL_POLICY_DIMENSIONS, GOAL_POLICY_SAFE_VALUES, legacyDimensionOverride } from '../../utils/goalPolicy.ts';
import { Input } from '../ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { GoalsPolicySection } from './GoalsPolicySection';

type GoalsPolicyEditorProps = {
  element: GoalElement;
  policyElement: GoalElement;
  effectivePolicy?: Pick<GoalPolicyV1, 'dimensions' | 'acceptance'> | null;
  runtimeProjection: GoalRuntimeProjectionLike | null;
  workspacePolicy?: GoalPolicyV1;
  policyImpact?: { requiresUserConfirmation?: boolean };
  onUpdateElement: (updates: Partial<GoalElement>) => void;
  onUpdatePolicy: (updates: Partial<GoalPolicy>) => void;
  onUpdatePolicyDimension: (dimension: GoalPolicyDimension, updates: GoalPolicyDimensionOverride | undefined) => void;
};

export function GoalsPolicyEditor({ element, policyElement, effectivePolicy, runtimeProjection, workspacePolicy, policyImpact, onUpdateElement, onUpdatePolicy, onUpdatePolicyDimension }: GoalsPolicyEditorProps) {
  return <GoalsPolicySection>
    <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">Policy</p>
    <p className="mt-1 text-[11px] text-slate-400">Typed controls become part of the execution contract.</p>
    {runtimeProjection?.execution && <p className="mt-2 rounded-md border border-slate-200 bg-slate-50 px-2.5 py-2 text-[11px] text-slate-600">Runtime: <span className="font-medium text-slate-800">{runtimeProjection.execution.state ?? 'unknown'}</span> · execution revision {runtimeProjection.execution.revision ?? 0} · policy revision {runtimeProjection.policyRevision ?? 0}</p>}
    {runtimeProjection?.lastChange?.errorCode && <p className="mt-2 rounded-md border border-red-200 bg-red-50 px-2.5 py-2 text-[11px] text-red-800">Conflict: <span className="font-semibold">{runtimeProjection.lastChange.errorCode}</span>. The rejected change remains inspectable and canonical state was preserved.</p>}
    {runtimeProjection?.execution?.reconciliationRequired && <p className="mt-2 rounded-md border border-orange-200 bg-orange-50 px-2.5 py-2 text-[11px] text-orange-800">Reconciliation required before execution can continue.</p>}
    {runtimeProjection?.execution?.state === 'approval-required' && <p className="mt-2 rounded-md border border-amber-200 bg-amber-50 px-2.5 py-2 text-[11px] text-amber-800">Approval required before this execution can proceed.</p>}
    {runtimeProjection?.execution?.state === 'blocked' && <p className="mt-2 rounded-md border border-amber-200 bg-amber-50 px-2.5 py-2 text-[11px] text-amber-800">Execution is blocked. Review the runtime policy, dependencies, and agent availability.</p>}
    {runtimeProjection?.agentAvailability?.some(item => !item.available) && <p className="mt-2 rounded-md border border-red-200 bg-red-50 px-2.5 py-2 text-[11px] text-red-800">Agent unavailable: dispatch remains blocked until the configured capability is available or an approved fallback is selected.</p>}
    {workspacePolicy && <p className="mt-2 rounded-md border border-blue-100 bg-blue-50/60 px-2.5 py-2 text-[11px] text-blue-800">Workspace policy revision {workspacePolicy.policyRevision} is the inherited baseline. Goal and gate values can only narrow it.</p>}
    {policyImpact && <p className="mt-2 rounded-md border border-amber-200 bg-amber-50 px-2.5 py-2 text-[11px] text-amber-800">Active execution has a pending policy impact. {policyImpact.requiresUserConfirmation ? 'Confirmation is required before the widened policy can apply.' : 'Pause and review the affected execution before continuing.'}</p>}
    {effectivePolicy && <div className="mt-3 rounded-lg border border-slate-200 bg-slate-50/70 p-2.5">
      <p className="text-[11px] font-medium text-slate-600">Effective policy</p>
      <div className="mt-2 space-y-1.5">{GOAL_POLICY_DIMENSIONS.map(dimension => { const explicit = policyElement.policy?.dimensions?.[dimension.key] ?? legacyDimensionOverride(policyElement.policy, dimension.key); const effective = effectivePolicy.dimensions[dimension.key]; const value = effective.constrained ? `${effective.mode} · ${effective.value} ${dimension.unit}` : 'Unbounded'; return <div key={dimension.key} className="flex items-center justify-between gap-2 text-[11px]"><span className="text-slate-500">{dimension.label}</span><span className="text-right text-slate-700"><span>{value}</span><span className="ml-1 text-slate-400">· {explicit ? 'Explicit override' : 'Inherited'}</span></span></div>; })}</div>
      <p className="mt-2 text-[11px] text-slate-500">Acceptance: <span className="font-medium text-slate-700">{effectivePolicy.acceptance.actor}</span><span className="ml-1 text-slate-400">· {policyElement.policy?.acceptanceActor ? 'Explicit override' : 'Inherited'}</span></p>
    </div>}
    {policyElement.type === 'goal' && <div className="mt-3 space-y-3">
      <p className="text-[11px] font-medium text-slate-500">Goal budget overrides</p>
      {GOAL_POLICY_DIMENSIONS.map(dimension => { const explicit = policyElement.policy?.dimensions?.[dimension.key]; const mode = explicit?.constrained === false ? 'unbounded' : explicit?.mode ?? '__default__'; const value = explicit?.constrained === true ? explicit.value : ''; return <div key={dimension.key} className="rounded-lg border border-slate-200 p-2.5"><label className="block text-xs font-medium text-slate-600">{dimension.label}<Select value={mode} onValueChange={nextMode => { if (nextMode === '__default__') onUpdatePolicyDimension(dimension.key, undefined); else if (nextMode === 'unbounded') onUpdatePolicyDimension(dimension.key, { constrained: false }); else onUpdatePolicyDimension(dimension.key, { constrained: true, mode: nextMode as Exclude<GoalBudgetMode, 'unbounded'>, value: explicit?.constrained === true ? explicit.value : GOAL_POLICY_SAFE_VALUES[dimension.key], unit: dimension.unit }); }}><SelectTrigger className="mt-1"><SelectValue placeholder="Use workspace default" /></SelectTrigger><SelectContent><SelectItem value="__default__">Use workspace default</SelectItem><SelectItem value="hard-cap">Hard cap</SelectItem><SelectItem value="goal-pool">Goal pool</SelectItem><SelectItem value="approval-required">Approval required</SelectItem><SelectItem value="unbounded">Unbounded</SelectItem></SelectContent></Select></label>{explicit?.constrained === true && <div className="mt-2 flex items-center gap-2"><Input type="number" min="0.01" step={dimension.key === 'financial' ? '0.01' : '1'} value={value} onChange={event => { const next = Number(event.target.value); if (Number.isFinite(next) && next > 0 && (dimension.key === 'financial' || Number.isInteger(next))) onUpdatePolicyDimension(dimension.key, { ...explicit, value: next, unit: dimension.unit }); }} aria-label={`${dimension.label} override value`} /><span className="text-[11px] text-slate-400">{dimension.unit}</span></div>}<span className="mt-1 block text-[11px] text-slate-400">Missing or cleared values inherit the workspace policy.</span></div>; })}
    </div>}
    <label className="mt-3 block text-xs font-medium text-slate-600">{element.type === 'approval-gate' ? 'Required approver' : 'Acceptance actor'}<Select value={policyElement.policy?.acceptanceActor ?? '__default__'} onValueChange={value => onUpdatePolicy({ acceptanceActor: value === '__default__' ? undefined : value as GoalPolicy['acceptanceActor'] })}><SelectTrigger className="mt-1"><SelectValue placeholder="Use goal default" /></SelectTrigger><SelectContent><SelectItem value="__default__">Use goal default</SelectItem><SelectItem value="human">Human</SelectItem><SelectItem value="agentic">Agentic</SelectItem><SelectItem value="both">Both</SelectItem></SelectContent></Select></label>
    {element.type === 'approval-gate' && <label className="mt-3 flex items-center gap-2 text-xs font-medium text-slate-600"><input type="checkbox" checked={element.approvalEvidenceRequired !== false} onChange={event => onUpdateElement({ approvalEvidenceRequired: event.target.checked })} /> Require evidence before approval</label>}
    <label className="mt-3 block text-xs font-medium text-slate-600">Retry budget<Select value={policyElement.policy?.retryBudgetMode ?? '__default__'} onValueChange={value => onUpdatePolicy({ retryBudgetMode: value === '__default__' ? undefined : value as GoalBudgetMode })}><SelectTrigger className="mt-1"><SelectValue placeholder="Use goal default" /></SelectTrigger><SelectContent><SelectItem value="__default__">Use goal default</SelectItem><SelectItem value="hard-cap">Hard cap</SelectItem><SelectItem value="goal-pool">Goal pool</SelectItem><SelectItem value="approval-required">Approval required</SelectItem><SelectItem value="unbounded">Unbounded</SelectItem></SelectContent></Select></label>
    {policyElement.policy?.retryBudgetMode !== 'unbounded' && <label className="mt-3 block text-xs font-medium text-slate-600">Max retries<Input type="number" min={1} step={1} value={policyElement.policy?.maxRetries ?? ''} onChange={event => onUpdatePolicy({ maxRetries: event.target.value === '' ? undefined : Math.max(1, Math.floor(Number(event.target.value))) })} className="mt-1" aria-describedby="max-retries-help" /><span id="max-retries-help" className="mt-1 block text-[11px] font-normal text-slate-400">Use a positive whole number. Leave unbounded selected to remove this limit.</span></label>}
  </GoalsPolicySection>;
}

type GoalRuntimeProjectionLike = { execution?: GoalRuntimeProjection['execution']; policyRevision?: number; agentAvailability?: GoalRuntimeProjection['agentAvailability']; lastChange?: GoalRuntimeProjection['lastChange'] };
